### ISSUE TITLE
Adding admins and customizing map-gen-settings

### ISSUE THREAD

**Issue by berghall** [predr/factorio-headless-snap#1]
Hi,
first of all, thanks for creating this snap image, was looking for something just like this.

Second of all, would you mind adding the ability to add admins in the config?, would really need that. I saw that the README includes this:
`snap set factorio-headless admins='["kovarex"]'`
but couldn't get that to work, (maybe was thought to be implemented? :D)

And also it would be great if you added the map-gen-settings also as customizable.

**Comment by predr** [comment]
Hi,

They removed admins from server-settings.json so I removed it from snap and store description and will remove from README. Searched on forum and it looks like server-adminlist.json should be used instead. I'll add it back in as a separate command factorio-headless.admins if that works.

I'll look into map-gen-settings but no promises.

**Comment by predr** [comment]
Added `factorio-headless.admins` with this new stable 1.1.19 release.

    factorio-headless.admins add berghall kovarex
    snap restart factorio-headless

I don't see a way to implement customizable map-settings and map-gen-settings that makes sense. Generating saves with customized `map-settings.json` and `map-gen-settings.json` files or using full client to generate save in GUI and then copy it to server makes more sense to me.
