### ISSUE TITLE
What is the load saves command?

### ISSUE THREAD

**Issue by ChunHungHK** [predr/factorio-headless-snap#2]
How to load save file?

**Comment by predr** [comment]
There isn't one. You have to stop server, remove existing saves, copy your save and start server again.

snap stop factorio-headless
sudo rm /var/snap/factorio-headless/current/data/saves/*
sudo cp ./your-save.zip /var/snap/factorio-headless/current/data/saves/_autosave1.zip
snap start factorio-headless
